# AC/DC powered ESP32 Relay Board x4
# https://devices.esphome.io/devices/AC-DC-ESP32-Relay-x4

substitutions:
  name: 'coder4'
  # Outputs
  gpio_code: 'GPIO32'
  gpio_led: 'GPIO23'
  gpio_led_invert: 'true'
  gpio_reverse: 'GPIO25'
  gpio_shunt: 'GPIO33'
  gpio_trigger: 'GPIO26'
  # Inputs
  gpio_zone: 'GPIO27'
  gpio_zone_invert: 'true'
  gpio_presignal: 'GPIO18'
  gpio_presignal_invert: 'true'
  gpio_presignal_pullup: 'true'
  # I2C (for OLED)
  gpio_scl: 'GPIO16'
  gpio_sda: 'GPIO17'
  # ADC button ladder
  gpio_buttons_adc: 'GPIO34'

packages:
  main: !include main.yaml
  fire: !include includes/effects_fire.yaml
  firecom: !include includes/effects_firecom.yaml
  buttons: !include includes/buttons_menu.yaml
  display: !include includes/display_oled.yaml
