# ESP32 38-pin devkit w/L298 dual H-bridge motor controller for SmartSync inversions
# Configured for: ADC resistor ladder buttons + Howe decoder

substitutions:
  name: 'coder1'
  # Outputs
  gpio_code: 'GPIO16'
  gpio_led: 'GPIO1'
  gpio_led_invert: 'false'
  gpio_reverse: 'GPIO13'
  gpio_shunt: 'GPIO17'
  gpio_trigger: 'GPIO19'
  # Inputs
  gpio_doorbell: 'GPIO35'
  gpio_zone: 'GPIO33'
  gpio_zone_invert: 'true'
  gpio_presignal: 'GPIO34'
  gpio_presignal_invert: 'false'
  # I2C (for OLED)
  gpio_scl: 'GPIO25'
  gpio_sda: 'GPIO27'
  # ADC button ladder (uses internal pullup, GPIO32/33 only)
  gpio_buttons_adc: 'GPIO32'
  # Howe decoder inputs (relay dry contacts)
  gpio_howe_oscillator: 'GPIO18'
  gpio_howe_signal: 'GPIO21'

packages:
  main: !include main.yaml
  buttons: !include includes/buttons_adc.yaml
  display: !include includes/display_oled.yaml
  howe: !include includes/howe_decoder.yaml
