# ESP32 Relay x2
substitutions:
  name: 'coder3'
  gpio_code: 'GPIO16'
  gpio_code_up: 'GPIO22'
  gpio_code_down: 'GPIO14'
  gpio_doorbell: 'GPIO35'
  gpio_fire_up: 'GPIO18'
  gpio_fire_down: 'GPIO21'
  gpio_led: 'GPIO23'
  gpio_led_invert: 'true'
  gpio_march_up: 'GPIO26'
  gpio_march_down: 'GPIO4'
  gpio_zone: 'GPIO33'
  gpio_zone_invert: 'true'
  gpio_reverse: 'GPIO13'
  gpio_scl: 'GPIO25'
  gpio_sda: 'GPIO27'
  gpio_shunt: 'GPIO17'
  gpio_toggle: 'GPIO19'
  gpio_trigger: 'GPIO32'
  toggle_follower: 'false'

<<: !include main.yaml
