# AC/DC powered ESP32 Relay Board x4 (doorbell configuration)
# https://devices.esphome.io/devices/AC-DC-ESP32-Relay-x4

substitutions:
  name: 'coderdoorbell'
  # Outputs
  gpio_code: 'GPIO32'
  gpio_led: 'GPIO23'
  gpio_led_invert: 'true'
  gpio_reverse: 'GPIO25'
  gpio_shunt: 'GPIO33'
  gpio_trigger: 'GPIO26'
  # Inputs
  gpio_doorbell: 'GPIO35'
  gpio_zone: 'GPIO27'
  gpio_zone_invert: 'true'
  gpio_presignal: 'GPIO34'
  gpio_presignal_invert: 'false'
  gpio_presignal_pullup: 'false'

packages:
  main: !include main.yaml
  doorbell: !include includes/effects_doorbell.yaml
