# ESP32 38-pin devkit w/custom MOSFET driver

substitutions:
  name: 'coder2001'
  # Outputs
  gpio_code: 'GPIO16'
  gpio_led: 'GPIO1'
  gpio_led_invert: 'false'
  gpio_reverse: 'GPIO13'
  gpio_shunt: 'GPIO17'
  gpio_trigger: 'GPIO19'
  # Inputs
  gpio_doorbell: 'GPIO35'
  gpio_zone: 'GPIO33'
  gpio_zone_invert: 'true'
  gpio_presignal: 'GPIO34'
  gpio_presignal_invert: 'true'
  # I2C (for OLED)
  gpio_scl: 'GPIO25'
  gpio_sda: 'GPIO27'
  # ADC button ladder
  gpio_buttons_adc: 'GPIO32'

packages:
  main: !include main.yaml
  buttons: !include buttons_adc.yaml
