# ESP32 Relay x2
# https://devices.esphome.io/devices/ESP32-Relay-X2

substitutions:
  name: 'coder3'
  # Outputs
  gpio_code: 'GPIO16'
  gpio_led: 'GPIO23'
  gpio_led_invert: 'true'
  gpio_reverse: 'GPIO13'
  gpio_shunt: 'GPIO17'
  gpio_trigger: 'GPIO32'
  # Inputs
  gpio_doorbell: 'GPIO35'
  gpio_zone: 'GPIO33'
  gpio_zone_invert: 'true'
  gpio_presignal: 'GPIO34'
  gpio_presignal_invert: 'false'
  # I2C (for OLED)
  gpio_scl: 'GPIO25'
  gpio_sda: 'GPIO27'
  # Panel buttons
  gpio_toggle: 'GPIO19'
  gpio_fire_up: 'GPIO18'
  gpio_fire_down: 'GPIO21'
  gpio_march_up: 'GPIO26'
  gpio_march_down: 'GPIO4'
  gpio_code_up: 'GPIO22'
  gpio_code_down: 'GPIO14'

packages:
  main: !include main.yaml
  fire: !include includes/effects_fire.yaml
  buttons: !include includes/buttons_gpio.yaml
  display: !include includes/display_oled.yaml
