# esp32 38pin devkit w/L298 dual H bridge motor controller for smartsync inversions
substitutions:
  name: 'coder1'
  gpio_code_up: 'GPIO22'
  gpio_code_down: 'GPIO14'
  gpio_fire_up: 'GPIO18'
  gpio_fire_down: 'GPIO21'
  gpio_led: 'GPIO1'
  gpio_led_invert: 'false'
  gpio_march_up: 'GPIO26'
  gpio_march_down: 'GPIO4'
  gpio_nac: 'GPIO33'
  gpio_relay: 'GPIO16'
  gpio_reverse: 'GPIO13'
  gpio_scl: 'GPIO25'
  gpio_sda: 'GPIO27'
  gpio_shunt: 'GPIO17'
  gpio_toggle: 'GPIO19'
  gpio_trigger: 'GPIO32'

<<: !include main.yaml
