# ESP32 38-pin devkit w/L298 dual H-bridge motor controller for SmartSync inversions

substitutions:
  name: 'coder1'
  # Outputs
  gpio_code: 'GPIO16'
  gpio_led: 'GPIO1'
  gpio_led_invert: 'false'
  gpio_reverse: 'GPIO13'
  gpio_shunt: 'GPIO17'
  gpio_trigger: 'GPIO32'
  # Inputs
  gpio_doorbell: 'GPIO35'
  gpio_zone: 'GPIO33'
  gpio_zone_invert: 'false'
  gpio_presignal: 'GPIO34'
  gpio_presignal_invert: 'false'
  gpio_code_reader: 'GPIO36'
  # I2C (for OLED)
  gpio_scl: 'GPIO25'
  gpio_sda: 'GPIO27'
  # Panel buttons
  gpio_toggle: 'GPIO19'
  gpio_fire_up: 'GPIO18'
  gpio_fire_down: 'GPIO21'
  gpio_march_up: 'GPIO26'
  gpio_march_down: 'GPIO4'
  gpio_code_up: 'GPIO22'
  gpio_code_down: 'GPIO14'

packages:
  main: !include main.yaml
  buttons: !include buttons_gpio.yaml
