# Example: ESP32 with individual GPIO buttons (7 GPIOs for 7 buttons)
#
# Hardware setup:
#   - Each button connects a GPIO to GND through a momentary switch
#   - Internal pullups are used
#   - See buttons_gpio.yaml for button mapping
#
# This uses more GPIOs than the ADC ladder approach but is simpler to wire.

substitutions:
  name: 'coder-gpio'
  # Outputs
  gpio_code: 'GPIO16'
  gpio_led: 'GPIO23'
  gpio_led_invert: 'false'
  gpio_reverse: 'GPIO13'
  gpio_shunt: 'GPIO17'
  gpio_trigger: 'GPIO32'
  # Inputs
  gpio_doorbell: 'GPIO35'
  gpio_zone: 'GPIO33'
  gpio_zone_invert: 'false'
  gpio_presignal: 'GPIO34'
  gpio_presignal_invert: 'false'
  # I2C (for OLED)
  gpio_scl: 'GPIO25'
  gpio_sda: 'GPIO27'
  # Panel buttons (directly wired to GPIO)
  gpio_toggle: 'GPIO19'
  gpio_fire_up: 'GPIO18'
  gpio_fire_down: 'GPIO21'
  gpio_march_up: 'GPIO26'
  gpio_march_down: 'GPIO4'
  gpio_code_up: 'GPIO22'
  gpio_code_down: 'GPIO14'
  # Pulse counter (for reading incoming codes)
  #gpio_code_reader: 'GPIO36'

packages:
  main: !include main.yaml
  buttons: !include includes/buttons_gpio.yaml
  display: !include includes/display_oled.yaml
  diagnostics: !include includes/diagnostics.yaml
  #pulse_counter: !include includes/pulse_counter.yaml
