# ADC resistor ladder panel buttons (7 buttons, 1 GPIO)
# Requires substitution: gpio_buttons_adc
#
# Hardware setup: 10 x 1K resistors in series from 3.3V to GND
# Buttons connect ADC pin to each tap point
# Use external 10K pullup from gpio_buttons_adc to 3.3V - no press reads 3.3V
#
# Wiring diagram:
#   3.3V
#    |
#   [1K]--- Toggle       (2.97V) <- most important, highest voltage
#   [1K]--- Fire Up      (2.64V)
#   [1K]--- Fire Down    (2.31V)
#   [1K]--- March Up     (1.98V)
#   [1K]--- March Down   (1.65V)
#   [1K]--- Code Up      (1.32V)
#   [1K]--- Code Down    (0.99V)
#   [1K]--- (future)     (0.66V)
#   [1K]--- (future)     (0.33V)
#   [1K]--- (future)     (0.00V)
#    |
#   GND
#
# All button common wires connect to gpio_buttons_adc

sensor:
  - platform: adc
    pin:
      number: ${gpio_buttons_adc}
      mode:
        input: true
    id: button_ladder
    name: "Button Ladder"
    internal: true
    update_interval: 20ms
    attenuation: 12db
    filters:
      - median:
          window_size: 7
          send_every: 1
      - delta: 0.05

binary_sensor:
  - platform: template
    name: "Toggle"
    lambda: |-
      float v = id(button_ladder).state;
      return (v >= 2.85 && v <= 3.05);
    filters:
      - delayed_on: 10ms
    on_press:
      - switch.toggle: toggle

  - platform: template
    name: "Fire Up"
    lambda: |-
      float v = id(button_ladder).state;
      return (v >= 2.60 && v <= 2.84);
    filters:
      - delayed_on: 10ms
    on_press:
      - script.execute:
          id: set_effect
          mode: up
          type: fire

  - platform: template
    name: "Fire Down"
    lambda: |-
      float v = id(button_ladder).state;
      return (v >= 2.35 && v <= 2.59);
    filters:
      - delayed_on: 10ms
    on_press:
      - script.execute:
          id: set_effect
          mode: down
          type: fire

  - platform: template
    name: "March Up"
    lambda: |-
      float v = id(button_ladder).state;
      return (v >= 2.05 && v <= 2.34);
    filters:
      - delayed_on: 10ms
    on_press:
      - script.execute:
          id: set_effect
          mode: up
          type: march

  - platform: template
    name: "March Down"
    lambda: |-
      float v = id(button_ladder).state;
      return (v >= 1.89 && v <= 2.10);
    filters:
      - delayed_on: 10ms
    on_press:
      - script.execute:
          id: set_effect
          mode: down
          type: march

  - platform: template
    name: "Code Up"
    lambda: |-
      float v = id(button_ladder).state;
      return (v >= 1.60 && v <= 1.88);
    filters:
      - delayed_on: 10ms
    on_press:
      - script.execute:
          id: set_effect
          mode: up
          type: code

  - platform: template
    name: "Code Down"
    lambda: |-
      float v = id(button_ladder).state;
      return (v >= 1.30 && v <= 1.59);
    filters:
      - delayed_on: 10ms
    on_press:
      - script.execute:
          id: set_effect
          mode: down
          type: code
