# SmartSync Protocol Effects
# L298 wiring: shunt=ENA, code_output=IN1, reverse=IN2
# +V = shunt ON, code ON, reverse OFF  (ENA=1, IN1=1, IN2=0)
# 0V = shunt OFF, code OFF, reverse OFF (ENA=0, disabled)
# -V = shunt ON, code OFF, reverse ON  (ENA=1, IN1=0, IN2=1)
# Command sent every 4th cycle, embedded after 2ms 0V sync

esphome:
  includes:
    - includes/smartsync.h
  on_boot:
    - priority: 100
      then:
        - lambda: |-
            id(code_effects).insert(id(code_effects).begin(), "Smart Sync Temporal");
            id(code_effects).insert(id(code_effects).begin(), "Smart Sync March");
            id(code_effects).insert(id(code_effects).begin(), "Smart Sync Horn On");
            id(code_effects).insert(id(code_effects).begin(), "Smart Sync Horn Off");
            id(code_effects).insert(id(code_effects).begin(), "Smart Sync");
            id(code_effects).insert(id(code_effects).begin(), "Shart Sync");

light:
  - id: !extend code
    effects:
      - lambda:
          name: Shart Sync
          update_interval: 0ms
          lambda: |-
            static int state = 0;
            if (initial_run) state = 0;
            if (state == 1 || state == 116 || state == 231 || state == 346 ||
                (state > 356 && state < 362) || (state > 367 && state < 373) ||
                (state > 378 && state < 384) || (state > 389 && state < 394) ||
                (state > 395 && state < 397)) {
              id(code_output).turn_off();
            } else {
              id(code_output).turn_on();
            }
            if (state == 394 || state == 395) {
              id(shunt).turn_off();
              id(reverse).turn_on();
            } else {
              id(shunt).turn_on();
              id(reverse).turn_off();
            }
            state = (state + 1) % 448;

      - lambda:
          name: Smart Sync
          update_interval: 1ms
          lambda: |-
            static SmartSync sync;
            sync.run(initial_run, id(shunt), id(reverse), id(code_output), SMARTSYNC_NONE);

      - lambda:
          name: Smart Sync Horn Off
          update_interval: 1ms
          lambda: |-
            static SmartSync sync;
            sync.run(initial_run, id(shunt), id(reverse), id(code_output), SMARTSYNC_HORN_OFF);

      - lambda:
          name: Smart Sync Horn On
          update_interval: 1ms
          lambda: |-
            static SmartSync sync;
            sync.run(initial_run, id(shunt), id(reverse), id(code_output), SMARTSYNC_HORN_ON);

      - lambda:
          name: Smart Sync March
          update_interval: 1ms
          lambda: |-
            static SmartSync sync;
            sync.run(initial_run, id(shunt), id(reverse), id(code_output), SMARTSYNC_MARCH);

      - lambda:
          name: Smart Sync Temporal
          update_interval: 1ms
          lambda: |-
            static SmartSync sync;
            sync.run(initial_run, id(shunt), id(reverse), id(code_output), SMARTSYNC_TEMPORAL);
